/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as boringcrypto from "./@boringcrypto";
import type * as contracts from "./contracts";

export type { boringcrypto };

export type { contracts };
export * as factories from "./factories";
export type { Domain } from "./@boringcrypto/boring-solidity/contracts/Domain";
export { Domain__factory } from "./factories/@boringcrypto/boring-solidity/contracts/Domain__factory";
export type { DictatorDAO } from "./contracts/DictatorDAO";
export { DictatorDAO__factory } from "./factories/contracts/DictatorDAO__factory";
export type { IERC20 } from "./contracts/DictatorDAOFlat.sol/IERC20";
export { IERC20__factory } from "./factories/contracts/DictatorDAOFlat.sol/IERC20__factory";
export type { Greeter } from "./contracts/Greeter";
export { Greeter__factory } from "./factories/contracts/Greeter__factory";
