/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DictatorDAO } from "./DictatorDAO";
export type { Domain } from "./Domain";
export type { IERC20 } from "./IERC20";
