/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as dictatorDaoFlatSol from "./DictatorDAOFlat.sol";
export * as interfaces from "./interfaces";
export { DictatorDAO__factory } from "./DictatorDAO__factory";
export { Greeter__factory } from "./Greeter__factory";
