/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type * as dictatorDaoFlatSol from "./DictatorDAOFlat.sol";
import type * as interfaces from "./interfaces";

export type { dictatorDaoFlatSol };

export type { interfaces };
export type { DictatorDAO } from "./DictatorDAO";
export type { Greeter } from "./Greeter";
